### ISSUE TITLE
akas.imdb.com

### ISSUE THREAD

**Issue by b0t12** [drftpd-ng/drftpd#125]
No IMDB announce due to using akas.imdb.com

**imdb.log**
```
ERROR 2020-04-18T11:10:13,129 [Thread-9] org.drftpd.commands.imdb.IMDBParser [] - 
java.io.IOException: Error for URL http://akas.imdb.com/title/tt7665428/reference
	at org.drftpd.util.HttpUtils.retrieveHttpAsString(HttpUtils.java:66) ~[master-3.4.2.jar!/:?]
	at org.drftpd.commands.imdb.IMDBParser.getInfo(IMDBParser.java:109) [org.drftpd.commands.imdb-3.4.2.jar!/:?]
	at org.drftpd.commands.imdb.IMDBParser.doNFO(IMDBParser.java:102) [org.drftpd.commands.imdb-3.4.2.jar!/:?]
	at org.drftpd.commands.imdb.IMDBUtils.populateIMDBInfo(IMDBUtils.java:148) [org.drftpd.commands.imdb-3.4.2.jar!/:?]
	at org.drftpd.commands.imdb.IMDBUtils.addMetadata(IMDBUtils.java:135) [org.drftpd.commands.imdb-3.4.2.jar!/:?]
	at org.drftpd.commands.imdb.IMDBUtils.getIMDBInfo(IMDBUtils.java:101) [org.drftpd.commands.imdb-3.4.2.jar!/:?]
	at org.drftpd.commands.imdb.IMDBThread.run(IMDBThread.java:47) [org.drftpd.commands.imdb-3.4.2.jar!/:?]
Caused by: java.net.UnknownHostException: akas.imdb.com: Name or service not known
```
From what has been advised in channel, the following two files need to be edited manually and re-built.

**IMDBParser.java**
```
	private static final String _baseUrl = "http://akas.imdb.com";
	private static final String _searchUrl = "http://akas.imdb.com/find?s=all&q=";
```

**IMDBinfo.java**
```
	while ((line = in.readLine()) != null) {
				if (line.length() == 0) {
					continue;
				}
			    line = line.toLowerCase();
				if (line.contains("/title/tt")) {
					url = "http://akas.imdb.com/title/" + line.replaceAll(".*/title/(tt\\d+).*", "$1");
					break;
				}
			}
```

**Comment by mvangoor** [comment]
Those urls should not be static in the code, but be configurable.

**Comment by b0t12** [comment]
to get !imdb and announce to work I amended http://akas.imdb.com/ to https://imdb.com/ cleaned and rebuilt.

Just the following two files required the amend IMDBParser.java & IMDBinfo.java

**Comment by Scitz0** [comment]
> Those urls should not be static in the code, but be configurable.

As the parsing is static I'm not sure what value making url configurable gives.
Parsing is more likely to be a breaking change than url. Making all parsing configurable would be nice but also more complicated.

**Comment by mvangoor** [comment]
> As the parsing is static I'm not sure what value making url configurable gives.
> Parsing is more likely to be a breaking change than url. Making all parsing configurable could be a good enhancement to the plugin.

Agreed, that's why I created #126 and no big change for the v3 train
