### ISSUE TITLE
Mediainfo issues

### ISSUE THREAD

**Issue by snabben** [drftpd-ng/drftpd#146]
Getting some wierd mediainfo errors  (17.12-1ubuntu0.1)
See log.

DEBUG 2020-05-19T14:30:27,181 [RemoteSlave - Slave] org.drftpd.master.RemoteSlave [] - Received: AsyncResponseException exception is - Unable to invoke the proper handler
ERROR 2020-05-19T14:30:27,182 [FtpConn thread 70252 from <iphidden> - pool-11021-thread-1] org.drftpd.master.RemoteSlave [] - Exception on slave that is unable to be h$
java.lang.Exception: Unable to invoke the proper handler
        at org.drftpd.protocol.slave.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:172) ~[?:?]
        at org.drftpd.slave.Slave.handleCommand(Slave.java:543) ~[?:?]
        at org.drftpd.slave.Slave.access$200(Slave.java:55) ~[?:?]
        at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:584) ~[?:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.drftpd.protocol.slave.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:168) ~[?:?]
        ... 4 more
Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
        at org.mp4parser.IsoFile.<clinit>(IsoFile.java:35) ~[?:?]
        at org.drftpd.protocol.mediainfo.common.MediaInfo.getMediaInfoFromFile(MediaInfo.java:221) ~[?:?]
        at org.drftpd.protocol.mediainfo.slave.MediaInfoHandler.getMediaInfo(MediaInfoHandler.java:49) ~[?:?]
        at org.drftpd.protocol.mediainfo.slave.MediaInfoHandler.handleMediaFile(MediaInfoHandler.java:42) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.drftpd.protocol.slave.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:168) ~[?:?]
        ... 4 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
        at org.java.plugin.standard.StandardPluginClassLoader.loadClass(StandardPluginClassLoader.java:396) ~[jpf-1.5.1.jar:1.5.2]
        at org.java.plugin.drftpd.SynchronizedPluginClassLoader.loadClass(SynchronizedPluginClassLoader.java:61) ~[drftpd-jpf-3.4.3.jar:3.4.3]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_242]
        at org.mp4parser.IsoFile.<clinit>(IsoFile.java:35) ~[?:?]
        at org.drftpd.protocol.mediainfo.common.MediaInfo.getMediaInfoFromFile(MediaInfo.java:221) ~[?:?]
        at org.drftpd.protocol.mediainfo.slave.MediaInfoHandler.getMediaInfo(MediaInfoHandler.java:49) ~[?:?]
        at org.drftpd.protocol.mediainfo.slave.MediaInfoHandler.handleMediaFile(MediaInfoHandler.java:42) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_242]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_242]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
        at org.drftpd.protocol.slave.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:168) ~[?:?]
        ... 4 more
DEBUG 2020-05-19T14:30:27,183 [FtpConn thread 70252 from <iphidden> - pool-11021-thread-1] org.drftpd.master.RemoteSlave [] - setOffline() Exception on slave that is u$
ERROR 2020-05-19T14:30:27,184 [RemoteSlave - Slave] org.drftpd.master.RemoteSlave [] - IOException reading AsyncResponse
java.net.SocketException: Socket closed
        at java.net.SocketInputStream.read(SocketInputStream.java:204) ~[?:1.8.0_242]
        at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_242]
        at sun.security.ssl.InputRecord.readFully(InputRecord.java:465) ~[?:1.8.0_242]
        at sun.security.ssl.InputRecord.read(InputRecord.java:503) ~[?:1.8.0_242]
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975) ~[?:1.8.0_242]
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933) ~[?:1.8.0_242]
        at sun.security.ssl.AppInputStream.read(AppInputStream.java:105) ~[?:1.8.0_242]
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[?:1.8.0_242]
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265) ~[?:1.8.0_242]
        at java.io.ObjectInputStream$PeekInputStream.peek(ObjectInputStream.java:2696) ~[?:1.8.0_242]
        at java.io.ObjectInputStream$BlockDataInputStream.peek(ObjectInputStream.java:3003) ~[?:1.8.0_242]
        at java.io.ObjectInputStream$BlockDataInputStream.peekByte(ObjectInputStream.java:3013) ~[?:1.8.0_242]
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1576) ~[?:1.8.0_242]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:465) ~[?:1.8.0_242]
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:423) ~[?:1.8.0_242]
        at org.drftpd.master.RemoteSlave.readAsyncResponse(RemoteSlave.java:1039) [master-3.4.3.jar!/:?]
        at org.drftpd.master.RemoteSlave.run(RemoteSlave.java:814) [master-3.4.3.jar!/:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
DEBUG 2020-05-19T14:30:27,184 [RemoteSlave - Slave] org.drftpd.master.RemoteSlave [] - setOffline() IOException reading AsyncResponse

**Comment by 0xzou** [comment]
That's regarding an missing lib from isoparser (slf4j-api and slf4j-simple). We have to include slf4j-api and slf4j-simple both in lib folder and plugin.xml from mediainfo plugin.
 
Just tested this on my test setup and its working fine (when uploading an file and when you open a folder with an mp4 inside).

[SAMPLE] /SECTION/RELEASE/Sample/sample.mp4 :: -OK-
-VIDEO- AVC : 1920x1080 @ 4000kb/s : 29.970(30000/1001)FPS : 16:9 : High@L4 : 1min5s
-AUDIO- Unknown : AAC @ 150kb/s Variable : 44.1kHz : 2ch

isoparser link without the slf4j lib
https://mega.nz/file/D4d2TaRQ#zAFCWTddlso2d3EfxGp713zOufvDbOJR8AwpxlsCHyE

PS: Im build isoparser with suport for the log4j from drftpd so less libs to update

**Comment by zc0nf** [comment]
which version? 3.4.3 or 4.0 beta 1 ?

**Comment by snabben** [comment]
This was on 3.4.3

**Comment by mvangoor** [comment]
We are not actively working on 3.4 train anymore. Is this issue still around with 4.0 beta 1?

**Comment by zc0nf** [comment]
@mvangoor works fine on 4.0 beta 1

@snabben you can use 0xzou patch or wait the 4.0 finale version
