### ISSUE TITLE
Connection reset / Broken pipe

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd#192]
**Describe the bug:**

```
DEBUG 2021-02-11T22:20:03,641 [FtpConn thread 61 from <iphidden> - pool-662-thread-1] org.drftpd.master.commands.dataconnection.DataConnectionHandler [] - IOException during transfer
org.drftpd.common.exceptions.TransferFailedException: Connection reset
        at org.drftpd.master.network.RemoteTransfer.getTransferStatus(RemoteTransfer.java:106) ~[drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.network.TransferState.getTransferStatus(TransferState.java:359) ~[drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.commands.dataconnection.DataConnectionHandler.transfer(DataConnectionHandler.java:994) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.commands.dataconnection.DataConnectionHandler.doSTOR(DataConnectionHandler.java:1132) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.master.commands.StandardCommandManager.execute(StandardCommandManager.java:223) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.network.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:580) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.drftpd.common.exceptions.TransferFailedException: Connection reset
        at org.drftpd.slave.network.Transfer.transfer(Transfer.java:447) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.receiveFile(Transfer.java:261) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.protocol.BasicHandler.handleReceive(BasicHandler.java:196) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.slave.protocol.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:184) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave.handleCommand(Slave.java:512) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:553) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        ... 1 more
Caused by: javax.net.ssl.SSLException: Connection reset
        at sun.security.ssl.Alert.createSSLException(Alert.java:127) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1680) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1054) ~[?:?]
        at java.io.InputStream.read(InputStream.java:218) ~[?:?]
        at org.drftpd.slave.network.ThrottledInputStream.read(ThrottledInputStream.java:67) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.transfer(Transfer.java:400) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.receiveFile(Transfer.java:261) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.protocol.BasicHandler.handleReceive(BasicHandler.java:196) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.slave.protocol.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:184) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave.handleCommand(Slave.java:512) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:553) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        ... 1 more
        Suppressed: java.net.SocketException: Broken pipe
                at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
                at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
                at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
                at java.net.Socket$SocketOutputStream.write(Socket.java:1051) ~[?:?]
                at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:82) ~[?:?]
                at sun.security.ssl.TransportContext.fatal(TransportContext.java:400) ~[?:?]
                at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
                at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
                at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1680) ~[?:?]
                at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1054) ~[?:?]
                at java.io.InputStream.read(InputStream.java:218) ~[?:?]
                at org.drftpd.slave.network.ThrottledInputStream.read(ThrottledInputStream.java:67) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
                at org.drftpd.slave.network.Transfer.transfer(Transfer.java:400) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
                at org.drftpd.slave.network.Transfer.receiveFile(Transfer.java:261) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
                at org.drftpd.slave.protocol.BasicHandler.handleReceive(BasicHandler.java:196) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
                at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
                at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
                at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
                at org.drftpd.slave.protocol.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:184) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
                at org.drftpd.slave.Slave.handleCommand(Slave.java:512) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
                at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:553) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
                at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.net.SocketException: Connection reset
        at sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323) ~[?:?]
        at sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350) ~[?:?]
        at sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803) ~[?:?]
        at java.net.Socket$SocketInputStream.read(Socket.java:981) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1434) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038) ~[?:?]
        at java.io.InputStream.read(InputStream.java:218) ~[?:?]
        at org.drftpd.slave.network.ThrottledInputStream.read(ThrottledInputStream.java:67) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.transfer(Transfer.java:400) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.receiveFile(Transfer.java:261) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.protocol.BasicHandler.handleReceive(BasicHandler.java:196) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.slave.protocol.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:184) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave.handleCommand(Slave.java:512) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:553) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        ... 1 more
DEBUG 2021-02-11T22:20:03,644 [FtpConn thread 61 from <iphidden>] org.drftpd.master.network.BaseFtpConnection [] - << AUTH TLS
DEBUG 2021-02-11T22:20:03,645 [FtpConn thread 61 from <iphidden> - pool-663-thread-1] org.drftpd.master.permissions.Permission [] - [Permission::check] aclUser: [%]
```

**To Reproduce:**
1. FXP some release

**DrFTPD:**
 - OS: Debian
 - Java version 15
 - DrFTPD version 4.0.0beta2

**FTP Client:**
 - SLFTP 1.5.7

**Comment by mvangoor** [comment]
Looks like that in the meantime this was addressed in a similar fashion to other ftpds....

https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8234226

10. A new System Property, "jdk.tls.acknowledgeCloseNotify", is added.

Please test this new setting by adding this to your master.(sh/bat) and slave.(sh/bat).

-Djdk.tls.acknowledgeCloseNotify=true
