### ISSUE TITLE
SSL Tag mismatch

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd#193]
**Describe the bug:**

```
DEBUG 2021-02-11T22:19:47,929 [FtpConn thread 61 from <iphidden> - pool-660-thread-1] org.drftpd.master.commands.dataconnection.DataConnectionHandler [] - IOException during transfer
org.drftpd.common.exceptions.TransferFailedException: Tag mismatch!
        at org.drftpd.master.network.RemoteTransfer.getTransferStatus(RemoteTransfer.java:106) ~[drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.network.TransferState.getTransferStatus(TransferState.java:359) ~[drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.commands.dataconnection.DataConnectionHandler.transfer(DataConnectionHandler.java:994) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.commands.dataconnection.DataConnectionHandler.doSTOR(DataConnectionHandler.java:1132) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor34.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.master.commands.StandardCommandManager.execute(StandardCommandManager.java:223) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.network.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:580) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: org.drftpd.common.exceptions.TransferFailedException: Tag mismatch!
        at org.drftpd.slave.network.Transfer.transfer(Transfer.java:447) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.receiveFile(Transfer.java:261) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.protocol.BasicHandler.handleReceive(BasicHandler.java:196) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.slave.protocol.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:184) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave.handleCommand(Slave.java:512) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:553) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        ... 1 more
Caused by: javax.net.ssl.SSLException: Tag mismatch!
        at sun.security.ssl.Alert.createSSLException(Alert.java:133) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:369) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:312) ~[?:?]
        at sun.security.ssl.TransportContext.fatal(TransportContext.java:307) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:122) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1491) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1456) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038) ~[?:?]
        at java.io.InputStream.read(InputStream.java:218) ~[?:?]
        at org.drftpd.slave.network.ThrottledInputStream.read(ThrottledInputStream.java:67) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.transfer(Transfer.java:400) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.receiveFile(Transfer.java:261) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.protocol.BasicHandler.handleReceive(BasicHandler.java:196) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.slave.protocol.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:184) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave.handleCommand(Slave.java:512) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:553) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        ... 1 more
Caused by: javax.crypto.AEADBadTagException: Tag mismatch!
        at com.sun.crypto.provider.GaloisCounterMode.decryptFinal(GaloisCounterMode.java:621) ~[?:?]
        at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1118) ~[?:?]
        at com.sun.crypto.provider.CipherCore.fillOutputBuffer(CipherCore.java:1055) ~[?:?]
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:943) ~[?:?]
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:491) ~[?:?]
        at javax.crypto.CipherSpi.bufferCrypt(CipherSpi.java:794) ~[?:?]
        at javax.crypto.CipherSpi.engineDoFinal(CipherSpi.java:730) ~[?:?]
        at javax.crypto.Cipher.doFinal(Cipher.java:2500) ~[?:?]
        at sun.security.ssl.SSLCipher$T12GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1656) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:260) ~[?:?]
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:181) ~[?:?]
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1491) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1456) ~[?:?]
        at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:1038) ~[?:?]
        at java.io.InputStream.read(InputStream.java:218) ~[?:?]
        at org.drftpd.slave.network.ThrottledInputStream.read(ThrottledInputStream.java:67) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.transfer(Transfer.java:400) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.network.Transfer.receiveFile(Transfer.java:261) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.protocol.BasicHandler.handleReceive(BasicHandler.java:196) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor4.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.slave.protocol.SlaveProtocolCentral.handleCommand(SlaveProtocolCentral.java:184) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave.handleCommand(Slave.java:512) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:553) ~[drftpd-slave-4.0-SNAPSHOT.jar:?]
        ... 1 more
```

**To Reproduce:**
1. FXP some release

**DrFTPD:**
 - OS: Debian
 - Java version 15
 - DrFTPD version 4.0.0beta2

**FTP Client:**
 - FTP software: SLFTP 1.5.7

**Comment by zc0nf** [comment]
Hello,
The problem has not reoccurred since.
We are closing this issue.
