### ISSUE TITLE
site new - comparison method violates its general contract

### ISSUE THREAD

**Issue by hrxcodes** [drftpd-ng/drftpd#204]
**Describe the bug**
`site new` does not work sometimes

```
ERROR 2021-03-21T15:57:26,120 [FtpConn thread 32 from <iphidden> - pool-121-thread-1] org.drftpd.master.commands.StandardCommandManager [] - Command site new failed: ''
java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.TimSort.mergeHi(TimSort.java:903) ~[?:?]
        at java.util.TimSort.mergeAt(TimSort.java:520) ~[?:?]
        at java.util.TimSort.mergeForceCollapse(TimSort.java:461) ~[?:?]
        at java.util.TimSort.sort(TimSort.java:254) ~[?:?]
        at java.util.Arrays.sort(Arrays.java:1306) ~[?:?]
        at java.util.ArrayList.sort(ArrayList.java:1720) ~[?:?]
        at org.drftpd.master.commands.newhandler.New.doNEW(New.java:128) ~[drftpd-master-4.0-SNAPSHOT.jar:?]
        at jdk.internal.reflect.GeneratedMethodAccessor95.invoke(Unknown Source) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
        at org.drftpd.master.commands.StandardCommandManager.execute(StandardCommandManager.java:223) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at org.drftpd.master.network.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:580) [drftpd-master-4.0-SNAPSHOT.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
        at java.lang.Thread.run(Thread.java:832) [?:?]
```

```
[16:57:14] site new
[16:57:15] 200- ----+-------+-----------+-------------+----------------------------------------
[16:57:15] 200-  ## |  Age  | Owner     | Files  Size | Directory Name
[16:57:15] 200- ----+-------+-----------+-------------+----------------------------------------
[16:57:15] 200- [ 1]  1.086s abcd          18F 245.3MB /XX/XX
[16:57:15] 200- [ 2]  1.176s abcde         21F 287.9MB /XX/XX
[16:57:15] 200- [ 3]  1.234s abcdeda       13F  95.5MB /XX/XX
[16:57:15] 200- [ 4]  1.378s asdb          21F 265.0MB /XX/XX
[16:57:15] 200- [ 5]  2.068s sdfgd         10F 117.1MB /XX/XX
[16:57:15] 200- -------------------------------------------------------------------------------
[16:57:15] 200 Command okay
[16:57:21] site new
[16:57:22] 540 Command execution failed
[16:57:25] site new
[16:57:26] 540 Command execution failed
[16:57:28] site new
[16:57:29] 540 Command execution failed
```

**To Reproduce**
Not sure, noticed these error messages in the logs as the master was starting and slaves remerging.

**DrFTPD**
 - OS: Ubuntu 20.04
 - Java version: 14
 - DrFTPD version 4.0.0 release

**Comment by mvangoor** [comment]
This is a complex one....
1. The only viable reason this happens is the private DateComparator doing something the 'contract' does not expect.
2. It's not reproducable

I read about the 'contract' here: https://stackoverflow.com/questions/11441666/java-error-comparison-method-violates-its-general-contract

I can see a situation on remerge where a vfs inode gets a new last modified and then violates the contract.

Still very complex one this
