### ISSUE TITLE
(RESOLVED) > java.lang.RuntimeException: Stats plugin is not loaded

### ISSUE THREAD

**Issue by MrBrain-g6** [drftpd-ng/drftpd#249]
**Describe the bug**
To be honest I don't know what this error means or causes BUT since this error has existed, the IRC announcements are no longer displayed correctly. The files in the INCOMING are available but the race is not displayed properly 

**To Reproduce**
1. master.log
ERROR 2021-10-19T10:10:46,177 [FtpConn thread 54 from <iphidden> - pool-107-thread-1] org.drftpd.master.commands.CommandInterface [] - Error while loading/invoking prehook [public org.drftpd.master.commands.CommandRequestInterface org.drftpd.statistics.master.StatsPreHook.doRETRPreHook(org.drftpd.master.commands.CommandRequest)], reason: java.lang.RuntimeException: Stats plugin is not loaded.
ERROR 2021-10-19T10:10:49,184 [FtpConn thread 54 from <iphidden> - pool-107-thread-1] org.drftpd.master.commands.CommandInterface [] - Error while loading/invoking posthook public void org.drftpd.statistics.master.StatsPostHook.doRETRPostHook(org.drftpd.master.commands.CommandRequest,org.drftpd.master.commands.CommandResponse)
java.lang.RuntimeException: Stats plugin is not loaded.
	at org.drftpd.statistics.master.StatsManager.getStatsManager(StatsManager.java:60) ~[drftpd-statistics-master-4.0.5-SNAPSHOT.jar:?]
	at org.drftpd.statistics.master.StatsPostHook.doRETRPostHook(StatsPostHook.java:48) ~[drftpd-statistics-master-4.0.5-SNAPSHOT.jar:?]
	at jdk.internal.reflect.GeneratedMethodAccessor62.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.drftpd.master.commands.CommandInterface.doPostHooks(CommandInterface.java:98) [drftpd-master-4.0.5-SNAPSHOT.jar:?]
	at org.drftpd.master.commands.StandardCommandManager.execute(StandardCommandManager.java:247) [drftpd-master-4.0.5-SNAPSHOT.jar:?]
	at org.drftpd.master.network.BaseFtpConnection$CommandThread.run(BaseFtpConnection.java:632) [drftpd-master-4.0.5-SNAPSHOT.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]

**Expected behavior**

**DrFTPD**
 - OS: Debian 11
 - openjdk 15.0.2 2021-01-19
 - OpenJDK Runtime Environment (build 15.0.2+7-27)
 - OpenJDK 64-Bit Server VM (build 15.0.2+7-27, mixed mode, sharing)
 - DrFTPD version >> DrFTPD 4.0.5

**Additional context**
**OLD:**
NEW in MP3: -> 1018/Music by user/group. ·
FIRST in MP3: -> 1018/Music by user/group @ 21.5MB/s. Expecting 64.7MB in 5 files. ·
iD3 in MP3: -> Music [House from 2021 at 320 kbit/s CBR Joint stereo] ·
RACE in MP3: -> user/group is joining on 1018/Music @ 29.8MB/s and 3 files left. ·
HALFWAY in MP3: -> 1018/Music at avg speed 45.7MB/s 1.372s with race leader trnk/FRiENDS [28.4MB/3F/60%/19.4MB/s] with 2 files left. ·
RACE in MP3: -> user/group is joining on 1018/Music @ 10.9MB/s and 1 files left. ·
COMPLETE in MP3: -> 1018/Music ( 73.4MB in 5F at avg speed 24.5MB/s 3.853s ) by 3 racer(s) from 2 group(s). ·
UserTop: ·
1. user/group 
2. user/group 
3. user/group 
GroupTop: ·
1. group
2. group

**NEW:**
NEW in MP3: -> 1019/Music by user/group. ·

Above as you can see the correct announce in irc and below only one line which appears in irc

**Comment by mvangoor** [comment]
This looks similar to https://github.com/drftpd-ng/drftpd/issues/247, please update to 4.0.6 and report back if that solves it

**Comment by MrBrain-g6** [comment]
Solution in my case: >> a complete reinstallation of drftpd.
