### ISSUE TITLE
R] 500- java.util.concurrent.ExecutionException:

### ISSUE THREAD

**Issue by stylezman** [drftpd-ng/drftpd#265]
slave goes offline while speedtest causing this errormessage

DrFTPD Slave starting, further logging will be done through log4j
Exception in thread "AsyncCommandHandler - class org.drftpd.common.network.AsyncCommandArgument" java.lang.NullPointerException: Cannot invoke "java.io.ObjectOutputStream.writeObject(Object)" because "this._sout" is null
        at org.drftpd.slave.Slave.sendResponse(Slave.java:578)
        at org.drftpd.slave.Slave$1AsyncCommandHandler.run(Slave.java:498)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by mvangoor** [comment]
Hello @stylezman,

Can you test this again with latest master (4.0.10-git).

If this still happens on this version please provide more log entries as this stack trace is only telling 50% of the story

**Comment by zc0nf** [comment]
Hello,
Having received no response to our question, we are closing this issue.
