### ISSUE TITLE
Blowfish Problem

### ISSUE THREAD

**Issue by zc0nf** [drftpd-ng/drftpd#84]
Sometimes blowfish no longer works :

IRC:
`<+donmagic1>\}!¦f$$·EãU;oHA0{a¿´Eê[²äû·±Ï(ޖ·ÝdfÑÏòp/M´tI~ʖ¬qWw¿8`

LOG:
`ERROR 2019-01-19 21:42:09,564 [SiteBot Command Handler-300 - Waiting for commands] org.drftpd.plugins.sitebot.blowfish.Blowfish  - Error encrypting
java.lang.IllegalStateException: Cipher not initialized
	at javax.crypto.Cipher.checkCipherState(Cipher.java:1749)
	at javax.crypto.Cipher.doFinal(Cipher.java:2156)
	at org.drftpd.plugins.sitebot.blowfish.BlowfishECB.encrypt(BlowfishECB.java:66)
	at org.drftpd.plugins.sitebot.BlowfishManager.encrypt(BlowfishManager.java:42)
	at org.drftpd.plugins.sitebot.OutputWriter.sendMessage(OutputWriter.java:62)
	at org.drftpd.plugins.sitebot.ServiceCommand.sendOutput(ServiceCommand.java:71)
	at org.drftpd.plugins.sitebot.ServiceCommand.printOutput(ServiceCommand.java:63)
	at org.drftpd.commands.zipscript.ZipscriptCommands.doSITE_RESCAN(ZipscriptCommands.java:230)
	at sun.reflect.GeneratedMethodAccessor1646.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.drftpd.commandmanager.StandardCommandManager.execute(StandardCommandManager.java:203)
	at org.drftpd.plugins.sitebot.SiteBot$CommandThread.run(SiteBot.java:3142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
INFO 2019-01-19 21:59:08,421 [SiteBot Command Handler-407 - Waiting for commands] org.drftpd.plugins.sitebot.SiteBot  - Reloading conf/plugins/irc/irccommands.conf, origin org.drftpd.commands.sitemanagement`

Thx @donmagic1

**Comment by epochyx** [comment]
Also it seems the private chats are not working in some conditions, or at all.

**Comment by donmagic1** [comment]
[SiteBot Command Handler-3374 - Waiting for commands] org.drftpd.plugins.sitebot.blowfish.Blowfish  - Error encrypting
java.lang.IllegalStateException: Cipher not initialized
	at javax.crypto.Cipher.checkCipherState(Cipher.java:1749)
	at javax.crypto.Cipher.doFinal(Cipher.java:2156)
	at org.drftpd.plugins.sitebot.blowfish.BlowfishECB.encrypt(BlowfishECB.java:66)
	at org.drftpd.plugins.sitebot.BlowfishManager.encrypt(BlowfishManager.java:42)
	at org.drftpd.plugins.sitebot.OutputWriter.sendMessage(OutputWriter.java:62)
	at org.drftpd.plugins.sitebot.ServiceCommand.sendOutput(ServiceCommand.java:71)
	at org.drftpd.plugins.sitebot.ServiceCommand.printOutput(ServiceCommand.java:63)
	at org.drftpd.commands.zipscript.ZipscriptCommands.doSITE_RESCAN(ZipscriptCommands.java:230)
	at sun.reflect.GeneratedMethodAccessor135.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.drftpd.commandmanager.StandardCommandManager.execute(StandardCommandManager.java:203)
	at org.drftpd.plugins.sitebot.SiteBot$CommandThread.run(SiteBot.java:3142)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zc0nf** [comment]
Fixed by @mvangoor https://github.com/drftpd-ng/drftpd/commit/d99fa963fc8aea2742dab00a645baa24da1c3717

**Comment by zc0nf** [comment]
Definitively fixed by @k-2-r https://github.com/drftpd-ng/drftpd/commit/050a9382a68254cfdc36a089bcc37babf424f34e

Thx @mvangoor and @k-2-r
